### ISSUE TITLE
SneedMC is not written in Rust

### ISSUE THREAD

**Issue by cozyGalvinism** [Sneederix/SneedMC#4]
### Operating System

Windows, macOS, Linux, Other

### Description of bug

I expected to find a launcher written in chad Rust but was met with disappointment when I saw that it's written it lame old virgin C++. If you follow the reproduction steps, you can see that the first command lists an alarming amount of *.cpp files. These are source code written in C++, an obsolete and dangerous programming language. The second command produces no output at all, which suggests that SneedMC is, in fact, not written in Rust. Rust is a modern, safe programming language, featuring fearless abstractions and zero-cost concurrency. It's objectively superior to C++ and every other language in every way, therefore SneedMC should be rewritten in Rust as soon as possible.

### Steps to reproduce

* In the PolyMC source directory, run `find -name '*.cpp'`, followed by `find -name '*.rs'`.

### Suspected cause

An alarming hostility against Rust.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by chuckium** [comment]
feature

**Comment by sneedium** [comment]
No city slickers allowed
